### ISSUE TITLE
[FEATURE] Improving User Experience: The Need for Prompts in Chain Components

### ISSUE THREAD

**Issue by Adarsh0127** [FlowiseAI/Flowise#1069]
Hey all developers,

I have some suggestions:

- Please consider adding prompts components to chain components, like the "conversation retrieval QA chain." We currently have prompts components, but when we need to include document loaders, there isn't an option to add prompts. While there is an "additional parameters" feature in the conversation retrieval QA chain, it doesn't work as I expected, and we can't add any examples. My suggestion is to add prompts components to chain components.

I also noticed we have a custom tool component, but I'm unsure how to make it function similarly to the prompt components :)

**Comment by HenryHengZJ** [comment]
are you trying to use Document loaded from document loader as part of prompt in Conversational Retrieval QA Chain system message?

an alternative would be using LLMChain + Prompt Template to do so, that way you can total control of the prompt. Take a look at the Prompt Chaining with Vector Store template in marketplace

**Comment by rvy474** [comment]
I tried this, and it was a good recommendation. It worked for me.

**Comment by mateusluizfb** [comment]
Going back to this, did you guys manage to add a memory using LLMChain + Prompt Template? The latest "Conversational Retrieval QA Chain" has a memory option, but it doesn't have a prompt template one. Asking this because I'm working on an if/else flow that would need two different prompt depending on the result, but I would like the flow to still have memory. 

I found that langchain has support for memory in LLMChain: https://python.langchain.com/docs/modules/memory/adding_memory

**Comment by rahulvs4000** [comment]
@mateusluizfb you're right. Im also trying to add an if/else flow to a retrieval qa chain, but since there's no option for a prompt in the retrieval qa chain, Im unable to connect the if-else flow to the QA chain.
