### ISSUE TITLE
It takes ages to load chatflows view

### ISSUE THREAD

**Issue by zeitderforschung** [FlowiseAI/Flowise#1247]
**Describe the bug**
Since the the chat history feature is available it takes several minutes to load the Chatflows view. The /api/v1/chatflows endpoint returns ca. 30mb of data, although we only have a dozen chatflows configured. We use the chatbot in production and the chat history / view messages tab contains a lot of conversations.

**To Reproduce**
Load Chatflows view.

**Expected behavior**
Chatflow view should load instantly and history shouldn't be included.

Is there a way to disable the chat history completely? BTW we also use the langsmith integration.

**Comment by HenryHengZJ** [comment]
The reason of the laggy performance is because of the document loaders that you've uploaded with your file. If you do a little experiment and remove the document loaders, you might find it load the chatflows fast.

Flowise currently save all the uploaded documents as base64 string to your chatflow. We will have an update to let users store to a local path and that will resolve the issues.
