### ISSUE TITLE
[FEATURE] Support for OpenAI compatible API's 

### ISSUE THREAD

**Issue by ranon-rat** [FlowiseAI/Flowise#1285]
# Why?
I have seen multiple API's that are compatible with the OpenAI api like [fireworks](https://www.fireworks.ai/) and it would be cool that  they could be used in flowise.
It will only need to configure the temperature, the url, the model name, and a few other parameters.

**Comment by nitromir** [comment]
Can I access the flow in flowise API as an OpenaI compatible API?

**Comment by peterclemenko** [comment]
> Can I access the flow in flowise API as an OpenaI compatible API?
> 
> I want to use api flowise as an endpoint instead of api openai.

i want this as well

**Comment by crashr** [comment]
I don't think this is so easy because the chat history is stored in the backend, i.e. Flowise or the corresponding nodes, instead of being included in the HTTP request each time. Instead, the request is linked to a saved conversation via a chatId. This cannot be mapped via an OpenAI-compliant API. Nevertheless, I have tried a really rudimentary approach in order to be able to use Flowise in Open-WebUI. It is still very shaky, but works at least to some extent. I will soon provide a tool that will enable you to change the chatId from Open-WebUI.

https://github.com/crashr/open-adapter
