### ISSUE TITLE
[FEATURE] URL path prefix

### ISSUE THREAD

**Issue by datariomj** [FlowiseAI/Flowise#1498]
**Describe the feature you'd like**
Is it possible to have a new environment variable that sets the URL path prefix of flowsie?

To serve it like `http://localhost:3000/flowsie` instead of just `http://localhost:3000`.
This would be useful for us to reuse our application load balancer. Thank you.

**Comment by automaton82** [comment]
It's usually called a subpath, and I have it implemented in different repo here:
https://github.com/LogiComposer/Flowise

Look specifically at https://github.com/FlowiseAI/Flowise/commit/82feedffc5a1a20b58eb5a117eeeb1aa26dd37b4

The caveat is you have to recompile it for each different subpath due to the way react router works, and if you're using the embed library it also won't work with subpaths without a small modification which you can see in https://github.com/FlowiseAI/FlowiseChatEmbed/commit/60b9c7356c4d02fd2a7e5d87af5852fe1d806373

I had PRs open for both repos to add this functionality but I wasn't able to keep them up to date due to large changes in the two repos so I closed them out.
