### ISSUE TITLE
[BUG] Unable to connect to PostgreSQL with self-signed SSL

### ISSUE THREAD

**Issue by efthymiosh** [FlowiseAI/Flowise#1598]
**Describe the bug**

We have been setting the env variable `PGSSLMODE` to `no-verify` for connecting to our self-signed PostgreSQL database.
After upgrading from 1.4.1 to 1.4.10 we observed the following error:

```bash
2024-01-23 19:34:32 [ERROR]: ❌ [server]: Error during Data Source initialization: no pg_hba.conf entry for host "***", user "***", database "flowise", no encryption
```

My investigation pinpointed to [this](https://github.com/FlowiseAI/Flowise/commit/735edab9ae5d85be3999978d1ae24b984cfcb5a1) commit, which sets `ssl: true/false`.

Configuring the `DATABASE_SSL` to `true` yields:

```bash
2024-01-23 20:47:26 [ERROR]: ❌ [server]: Error during Data Source initialization: self-signed certificate in certificate chain
Error: self-signed certificate in certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1659:34)
    at TLSSocket.emit (node:events:517:28)
    at TLSSocket._finishInit (node:_tls_wrap:1070:8)
    at ssl.onhandshakedone (node:_tls_wrap:856:12)
```

It seems like `PGSSLMODE` is now ignored.

**To Reproduce**

1. Set-up a postgresql with a self-signed SSL certificate
2. Configure the postgresql datasource with `DATABASE_SSL=true`
3. Configure `PGSSLMODE=no-verify`

**Expected behavior**
Successful datasource connection.

**Screenshots**
N/A

**Flow**
N/A

**Setup**
-   Installation: docker/k8s with flowiseai/flowise:1.4.10
-   Command: sh -ec "flowise start"
-   Flowise Version 1.4.10
-   OS: Linux
-   Browser N/A

**Additional context**
N/A

**Comment by HenryHengZJ** [comment]
do we have `PGSSLMODE` env variable in Flowise?

**Comment by Jaredude** [comment]
> do we have `PGSSLMODE` env variable in Flowise?

PGSSLMODE is read in by the pg npm library, and it cannot be combined when we add ssl to the connection (line 81 of the connection-parameters.js file in the pg library.

@HenryHengZJ  I'll make another PR for supporting self-signed certificates via an env var with the cert as a base64 string like we discussed in the original PR, following [these guidelines](https://node-postgres.com/features/ssl).

@efthymiosh Since you have a self signed Postgres server will you be able to help test this? The setup would be that there will be an env var DATABASE_SSL_KEY_BASE64 which will need to be the self-signed client cert as a base64 string. By passing that string in, the pg client will use ssl and connecting using the self-signed certificate.

**Comment by Jaredude** [comment]
@HenryHengZJ The approach I took was to add the support for proper self signed cert, which takes priority over the simple ssl: true option (current implementation) and then defaults to adding nothing to the pg connection if neither are provided, allowing the usage of any PGSSLMODE used by the pg npm library, including the unrecommended no-verify option mentioned above and in other issues/discussions.

@efthymiosh This PR should allow for you to continue using PGSSLMODE=no-verify without having to add anything else to your env file.

**Comment by scheung38** [comment]
Hi @HenryHengZJ 

Is this issue still open? When trying to connect to PostgreSQL:

[ERROR]: [server]: Error: error: no pg_hba.conf entry for host "***", user "***", database "***)", SSL off
Error: error: no pg_hba.conf entry for host "***", user "***", database "***)", SSL off
    at buildLangchain ($HOME/data-talk-flowise/node_modules/flowise/dist/utils/index.js:331:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.buildChatflow ($HOME/data-talk-flowise/node_modules/flowise/dist/index.js:1496:40)
    at async $HOME/data-talk-flowise/node_modules/flowise/dist/index.js:1054:13
    
Did add:

SHOW hba_file;
hba_file                                 
--------------------------------------------------------------------------
$HOME/Library/Application Support/Postgres/var-16/pg_hba.conf:
 
Added:
 
# TYPE DATABASE USER CIDR-ADDRESS  METHOD
host  all  all 0.0.0.0/0 scram-sha-256   


In postgresql.conf:

listen_addresses = '*' 
port = 5432	

restarted postgreSQL

![Screenshot 2024-02-09 at 00 18 46](https://github.com/FlowiseAI/Flowise/assets/1273014/a2b1e28a-bbe9-4ced-b393-0be2f89fef1f)

**Comment by Jaredude** [comment]
> Hi @HenryHengZJ
> 
> Is this issue still open? When trying to connect to PostgreSQL:
> 
> [ERROR]: [server]: Error: error: no pg_hba.conf entry for host "_**", user "**_", database "_**)", SSL off Error: error: no pg_hba.conf entry for host "**_", user "_**", database "**_)", SSL off at buildLangchain ($HOME/data-talk-flowise/node_modules/flowise/dist/utils/index.js:331:19) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async App.buildChatflow ($HOME/data-talk-flowise/node_modules/flowise/dist/index.js:1496:40) at async $HOME/data-talk-flowise/node_modules/flowise/dist/index.js:1054:13
> 
> Did add:
> 
> ## show hba_file;
> hba_file
> $HOME/Library/Application Support/Postgres/var-16/pg_hba.conf:
> 
> Added:
> 
> TYPE DATABASE USER CIDR-ADDRESS METHOD host all all 0.0.0.0/0 scram-sha-256
> 
> In postgresql.conf:
> 
> listen_addresses = '*' port = 5432
> 
> restarted postgreSQL
> 
> ![Screenshot 2024-02-09 at 00 18 46](https://private-user-images.githubusercontent.com/1273014/303518669-a2b1e28a-bbe9-4ced-b393-0be2f89fef1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MTY1MTEsIm5iZiI6MTcwNzUxNjIxMSwicGF0aCI6Ii8xMjczMDE0LzMwMzUxODY2OS1hMmIxZTI4YS1iYmU5LTRjZWQtYjM5My0wYmUyZjg5ZmVmMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDlUMjIwMzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmRjYTliNWNkMDg1ZmYzMjRlNjFlNjNmODgzZjIzOTJiZTM5YzBjNThhZmZjMzZmMDE1YzRjMGExNjliYmYzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dP-7CnBbDknCj1XsiQmhqTn4DaiV858ao3K1F9F6qTI)

The issue you're encountering is with the Sql Database Chain node whereas this issue is related to Postgres for hosting your flowise data. The Sql Database Chain uses langchain/sql_db to connect to Postgres. While that package does support connecting using ssl and a self-signed ca, there is currently nothing in the node that would allow you to add your cert to the connection. However, it is using typeorm's PostgresConnectionOptions, which defaults to using the pg library, which does afford you the use of the env variable PGSSLMODE. You can view the options here: https://github.com/brianc/node-postgres/blob/master/packages/pg/lib/connection-parameters.js

Hope that helps

**Comment by dasheck0** [comment]
Had the same issue and finally fixed it. I am using an AWS RDS and had to add a configuration group in order to override the ssl settings. See https://stackoverflow.com/a/77787495 But the important part is setting the correct configuration for the postgres vector node. Turns out it uses typeorm under the hood. Therefore you have to provide the correct configuration (see screenshot).

<img width="557" alt="image" src="https://github.com/user-attachments/assets/17476f40-d8af-4159-aa71-9a0a610f09b4">

After this the issue was resolved.
