### ISSUE TITLE
[BUG] Chat history should be manage at backend if ChatId or Session id is getting passed in api calls.

### ISSUE THREAD

**Issue by navinkeshari** [FlowiseAI/Flowise#1666]
Construct a sequence involving memory nodes and conversation nodes. Initiate a conversation via the REST API, providing the chat ID or session ID after the initial call response. The flow fails to maintain the same context and instead alters the context. To handle context changes, the backend requires the passing of a chat_history list, potentially leading to an increase in request bandwidth. The system should retrieve chat details based on the chat or session ID.

**Comment by HenryHengZJ** [comment]
agree! we will work on that improvement!

**Comment by emrahtoy** [comment]
also related with #1584

**Comment by yos1p** [comment]
Thumbs up on this. Very important.

**Comment by HenryHengZJ** [comment]
This is now available in `v1.6.5`, every memory nodes now have a `sessionId` and automatically retrieve the chat history with it. This removes the need for passing `history` array in the API request

**Comment by emrahtoy** [comment]
Much appreciated, thank you.

**Comment by haimco50** [comment]
> This is now available in `v1.6.5`, every memory nodes now have a `sessionId` and automatically retrieve the chat history with it. This removes the need for passing `history` array in the API request

thanks! @HenryHengZJ  - what about context field on any other node fields initialized as part of  any sessionId  conversation - are those will be resored as well when passing a sessionId in a new conversation - trying to figure out how session tracking realy works - it seems to be working for chat hostory but not for context field for example - not sure whether this is bug or by design.
