### ISSUE TITLE
[FEATURE] Export all your Charts, Credentials, Variables and Custom Tools at once. 

### ISSUE THREAD

**Issue by toi500** [FlowiseAI/Flowise#1984]
**Describe the feature you'd like**
If you have an instance with, lets say, 20 bots, exporting one by one with all their credential, variables, tools, etc, can be quite tedious and ineffective. 

I recently suffered a crash on Railway out of the blue and redeploying did not help.

**Additional context**
If this cant be done, at least to be able to export all the credential at once so you can rebuild quickly.

**Comment by automaton82** [comment]
There used to be a button in the settings on the home page (chatflows) to export all of them, but I believe it was removed in a later version.

But you should probably just backup the database itself if you want to migrate.

**Comment by meokey** [comment]
> There used to be a button in the settings on the home page (chatflows) to export all of them, but I believe it was removed in a later version.
> 
> But you should probably just backup the database itself if you want to migrate.

or, mapping /root/.flowise volume to a folder on the host, I believe, also works.

**Comment by FacuBozzi** [comment]
> the easiest way is to get the database file itself

How do we do that?

**Comment by phish77** [comment]
I also needed persistence and a way to backup, as I'm running various flowise docker containers due to lack of multi-user support atm. So I made the /root/.flowise folder in the container available on the host by starting the docker container with docker RUN adding the argument

  -v /root/flowise-persistent:/root/.flowise.    #or your host folder of choice

So when deploying another flowise  instance with that same argument, I have all my templates back and also the credentials/API-keys. (btw., I added different user folders within /root/flowise-persistent/...)

Also, I'm more easily able to backup my user data by simply backing up /root/flowise-persistent.

@HenryHengZJ Is that a recommended way of doing this? Did I miss anything?

Thanks in advance and a big thanks for flowise!! Great product!
Ben
