### ISSUE TITLE
[BUG] Unable to connect to Postgres-DB in Chatflow module

### ISSUE THREAD

**Issue by rubrix** [FlowiseAI/Flowise#2295]
**Describe the bug**

**Reference https://github.com/FlowiseAI/Flowise/issues/2013**

I have added the vector extension but still get the same error... is this because I am use a self-signed certificate? what is the correct parameter for that? I just have sslmode=require exactly as above.. I'm using a hosted postgresdb.

**Steps to reproduce the behavior:**

1. Add credentials for Postgres
2. Add Postgres module to Chatflow
3. Add host (tried external subdomain, localhost and IP), DB, port
4. Additional parameters: sslmode="require" + add table name
5. Save chatflow
6. Upsert
7. Error: error: pg_hba.conf rejects connection for host "XX", user "XX", database "XX", no encryption

**Expected behavior**
Postgres-DB connection is working

**Setup**

Flowise Version 1.6.2
npm

<img width="216" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/31581079/90f5902d-7984-45f1-b35d-a80fd5eb347c">

_Originally posted by @rubrix in https://github.com/FlowiseAI/Flowise/issues/2013#issuecomment-2085163589_

**Comment by HenryHengZJ** [comment]
perhaps you need PGSSLMODE? https://github.com/FlowiseAI/FlowiseDocs/pull/65

**Comment by rubrix** [comment]
I tried that as well like this:

<img width="809" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/31581079/6f830440-9ef7-43ed-b777-069c38934be5">

but still receive an error..

<img width="398" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/31581079/54b46284-7d68-4586-8be4-39150d1de578">

**Comment by dasheck0** [comment]
Had the same issue and finally fixed it. I am using an AWS RDS and had to add a configuration group in order to override the ssl settings. See https://stackoverflow.com/a/77787495 But the important part is setting the correct configuration for the postgres vector node. Turns out it uses typeorm under the hood. Therefore you have to provide the correct configuration (see screenshot).

<img width="315" alt="image" src="https://github.com/user-attachments/assets/bb90f837-f2dc-4bbf-950e-3c9ceaafd036">

After this the issue was resolved.
