### ISSUE TITLE
MY LLM-OPENAI- MODEL NAME shows "no  option",Can someone help me？TT

### ISSUE THREAD

**Issue by liyiyiya** [FlowiseAI/Flowise#2384]
![image](https://github.com/FlowiseAI/Flowise/assets/166470931/e7a01cd1-d5ba-44bf-ab92-9b02ddbd6b58)

**Comment by HenryHengZJ** [comment]
by default, flowise retrieves the list of models from a [file](https://raw.githubusercontent.com/FlowiseAI/Flowise/main/packages/components/models.json) and I guess due to proxy constraint your machine was not able to fetch the file, you can configure an env variable to specify your own path - https://docs.flowiseai.com/configuration/environment-variables#models

**Comment by liyiyiya** [comment]
> by default, flowise retrieves the list of models from a [file](https://raw.githubusercontent.com/FlowiseAI/Flowise/main/packages/components/models.json) and I guess due to proxy constraint your machine was not able to fetch the file, you can configure an env variable to specify your own path - https://docs.flowiseai.com/configuration/environment-variables#models

hello ，I tried, but it still didn't work TT
![image](https://github.com/FlowiseAI/Flowise/assets/166470931/87fe78a7-c351-4dbf-8450-9c2a4832cb66)
