### ISSUE TITLE
[FEATURE] Ability to upload text,csv or pdf by endusers

### ISSUE THREAD

**Issue by mahmoudsorf** [FlowiseAI/Flowise#2763]
Currently with simple text file uploads (applicable to pdf and csv files as well) The text needs to be converted to embeddings, stored to a vector DB then the chatbot can be used/published. If we can make this first step executed automatically if a user uploaded a text file within the embed-chat itself it would really be a huge improvement (of course file size limits should apply). 

![image](https://github.com/FlowiseAI/Flowise/assets/141017916/5ea17807-dcae-4254-8d08-a5cbf957d8f4)

**Comment by HenryHengZJ** [comment]
same as - https://github.com/FlowiseAI/Flowise/issues/2444

**Comment by haimco50** [comment]
Same as https://github.com/FlowiseAI/Flowise/issues/2084 as well :-)
@HenryHengZJ - would it work by calling the Flowise API ? (i.e instead of passing base64 encoded image will pass PDF url or whatever Claude needs to support this) - any work around you could think of?
btw, with the multi modality ramping up quickly this should be an higher priority item.

**Comment by haimco50** [comment]
@HenryHengZJ - I took a look at Anthropic Claude API doc and it looks like the Create message API accepts either text or based64 encoded image which means that in order to support PDF/None image format they had to do some pre-processing extraction activity of text/images before calling the API so is this the way to plan to support this or maybe you plan on using some kind of embedding technique etc.. - I have a use case of PDF files that have only images in it (scanned documents) so I need to figure out the base way to support this - I can extract images from the PDF (one image for each PDF page) and then call the  API with the extracted images but I am not sure this is the most effective way dealing with this request.

**Comment by HenryHengZJ** [comment]
Closing as https://github.com/FlowiseAI/Flowise/pull/3059 merged!

**Comment by haimco50** [comment]
Wow - finally !! this is really amazing
