### ISSUE TITLE
Example usage of the huggingface node?

### ISSUE THREAD

**Issue by ApieDePapie** [FlowiseAI/Flowise#28]
Is there any guide or example on how to use the Huggingface node that is included? I can't select more than the gpt2 model in the dropdown. and I can't input anything without it disappearing? I tried to adjust it in the code manually but I got an error with no code while fetching after a while of loading.

**Comment by HenryHengZJ** [comment]
I've updated the HF LLM model (https://github.com/FlowiseAI/Flowise/pull/29) as a textfield instead of dropdown. This allow you to enter any model name you want to use from HF. Example:

![screely-1682193348105](https://user-images.githubusercontent.com/26460777/233804401-e5f00892-4a46-4e12-8a8d-537fe205492d.png)

However the model answer is a lil bit strange and incomplete as compared to OpenAI model

**Comment by ApieDePapie** [comment]
Awesome! I will try it out!
