### ISSUE TITLE
[BUG] Ollama Connection

### ISSUE THREAD

**Issue by baeckerman83** [FlowiseAI/Flowise#3108]
**Describe the bug**
I installed Flowise locally and Ollama in a docker container. Ollama API is reachable from other PCs in the same network. Also it is possible to reach Ollama API from the PC where flowise is installed. But in flowise I get 404 when i want to use the API.
I used the url http://10.0.3.40:11434/ for bot inside the node and with curl. 

**Expected behavior**
A tought ollama should be reachable with the node when it is reachable with curl.

**Setup**

-   Installation Flowisefrom PackageManager, ollama in Docker
-   Flowise Version 1.8.3
-   OS: Linux

**Comment by ryanhalliday** [comment]
If they are both running in docker containers you need to use docker to give them each access unless you use something like `host.docker.internal` (Mac / Windows). Otherwise docker separates the containers from being able to access each other. 

Add them to the same docker network or make one depend on the other inside docker compose and use the container names as their hostnames. 

eg https://stackoverflow.com/questions/41093812/how-to-get-docker-containers-to-talk-to-each-other-while-running-on-my-local-hos

**Comment by baeckerman83** [comment]
Hi!
Flowise is running in docker. But Ollama not. Ollama is running direct on the server.

**Comment by ryanhalliday** [comment]
Then you need to refer to ollama with `host.docker.internal:port` for MacOS/Windows. For Linux you'll need to setup a host network for the container. Replace port with the port number.

Can you please close this issue?
