### ISSUE TITLE
Document Store shows nothing after add New one

### ISSUE THREAD

**Issue by sinanalmac** [FlowiseAI/Flowise#3294]
Hello  All,
I'm using brand new windows 11. yesterday I installed  Node js and updated it.  FlowWise worked but. I can not add a new document . Actually it says    "Ne document Store created"  but not shown on the interface.

No error on terminal:

2024-10-02 10:52:08 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
2024-10-02 10:52:08 [INFO]: 📦 [server]: Data Source is being initialized!
2024-10-02 10:52:16 [INFO]: 📦 [server]: Data Source has been initialized!
2024-10-02 10:52:59 [INFO]: ⬆️ POST /api/v1/document-store/store
 
 İs there any one to know?
 I formatted the computer and reinstalled all several times. 
 
![image](https://github.com/user-attachments/assets/002bdbc2-a13f-460d-b80d-560fae61f544)

**Comment by sinanalmac** [comment]
Develeop vesion is workinbg

**Comment by nikolatesla20** [comment]
Same issue here on Windows 11 system

**Comment by HenryHengZJ** [comment]
Just tried `npm install -g flowise` and `npx flowise start`, I can create and see doc store:
![image](https://github.com/user-attachments/assets/d94fd99a-e802-4cf8-9528-5ce51253b1da)

Not sure if this some sort of cache problem, but try igconito or other browser?

**Comment by OpeyemiSanusi** [comment]
Having the same issue at the moment any fix?

**Comment by OpeyemiSanusi** [comment]
> p vesion

what do you mean by Develop version

**Comment by OpeyemiSanusi** [comment]
**Got Flowise Working After Several Attempts**

After trying various approaches, I was finally able to get Flowise working. Here's what I did:

1. **Switched Node Version:** I switched to Node.js version `18.20.4`, which is compatible with Flowise.
  
2. **Folder Location:** Instead of installing Flowise in a subdirectory within `Documents` or `Downloads`, I created a folder in my root directory at `~/User/AI/`. This ensured the installation had the necessary permissions without requiring `sudo`.

3. **Installation:** I navigated to the `AI` folder via terminal and ran the following command:
   ```bash
   npm install -g flowise
   ```

This approach solved the issue but tbh after trying so many things I am not entirely sure if this is all you'd need, but try it and don't downgrade your nodeJS version first, try installing in a root folder and if that doesn't work then downgrade then install in the root folder

**Comment by vannoo67** [comment]
Thanks @OpeyemiSanusi I can confirm that uninstalling Node.js version 22.8.0 and installing version 18.20.4 and no other changes  fixed this problem.

**Comment by sinanalmac** [comment]
Thank you @OpeyemiSanusi  your solution is worked on my end

**Comment by sinanalmac** [comment]
> 18.20.4 an
 that  version
![image](https://github.com/user-attachments/assets/63969272-6c55-4e07-8f1b-1aa7df6b35a2)

**Comment by jai3232** [comment]
If you don't want to downgrade the nodejs. Try install direct from github.

Clone the Repository
`git clone https://github.com/FlowiseAI/Flowise.git`
`cd Flowise`

Install Dependencies
`npm install -g pnpm`

Then, install all dependencies
`pnpm install`

Build the Code
`pnpm build`

Start the Application
`pnpm start`

**Comment by Rao-abhinandan** [comment]
> I can confirm that uninstalling Node.js version 22.8.0 and installing version 18.20.4 and no other changes fixed this problem.

This worked for me too

**Comment by caduguimaraes** [comment]
I'm also facing the same problem btw.

**Comment by home-apps** [comment]
Hi @HenryHengZJ, could you please share with us a way (guide) to fix this issue, for people using local and cloud hosting. It seems like many of the issues related to datastores and data are linked to the different nodejs versions used by Flowise and the local installs/cloud hosts. It is now a few months since this happens. Solutions for Riley and Render would be very much appreciated. Thank you!
