### ISSUE TITLE
[FEATURE] - Support open-ai Realtime API

### ISSUE THREAD

**Issue by niztal** [FlowiseAI/Flowise#3303]
### Description: 
Open AI just announced the new GPT 4o Realtime API, which brings superb capabilities of Speech to Speech, Speech to Text, Text to Speech combining functions/tools as well.

Seems like this model is based on web socket openai's API.

I really think combining this capabilities would gain huge value to flowise having the option to build RAG+commands voice applications

### Additional Info:

1. [Announcement](https://openai.com/index/introducing-the-realtime-api/)
2. [API doc](https://platform.openai.com/docs/guides/realtime/overview)

@HenryHengZJ 

Thanks

**Comment by niztal** [comment]
I just saw some solution proposed by lang chain based on ReAct agent

https://github.com/langchain-ai/react-voice-agent

**Comment by HenryHengZJ** [comment]
no access yet 😢

**Comment by niztal** [comment]
@HenryHengZJ not sure I'm following, no access to what?

Thanks

**Comment by HenryHengZJ** [comment]
We've created a demo apps using Flowise: https://x.com/FlowiseAI/status/1843313761698140610

https://github.com/FlowiseAI/openai-realtime-console

It has to be standalone project. At this stage, we are not able to integrate the whole realtime websocket into Flowise. This is because there is no way to create multiple websockets, each with different API keys, all using one single HTTP server backend.
