### ISSUE TITLE
[BUG] Error: documentStoreServices.insertIntoVectorStore TypeError: fetch failed

### ISSUE THREAD

**Issue by MaciekStrzelbicki** [FlowiseAI/Flowise#3337]
**Describe the bug**
After creating chunks
<img width="1318" alt="image" src="https://github.com/user-attachments/assets/672a4ab5-2293-4704-98ef-68222e23e384">

im trying upsert to db
<img width="1318" alt="image" src="https://github.com/user-attachments/assets/ddd1ef9a-e50d-42de-a526-9f853767f00e">

no matter on db (also tried local chromadb) - same error
<img width="1318" alt="image" src="https://github.com/user-attachments/assets/edf36be9-58e3-499b-9604-ecfbf93534fd">

Status: 500
Error: documentStoreServices.insertIntoVectorStore - Error: documentStoreServices._insertIntoVectorStoreWorkerThread - TypeError: fetch failed

also tried another splitting (now its 500/100)  - same error
and different embedings model  - same error

**Setup**
-   Installation docker,
-   Flowise Version 2.1.2
-   OS: macOS,
-   Browser Opera

**Comment by ChristianKniep** [comment]
@MaciekStrzelbicki How did you solve this? Got the same error following the tutorial here: https://www.youtube.com/watch?v=lJOZiRoZNJw

**Comment by KALULOLO** [comment]
I'm in the same condition to @ChristianKniep, got the same error after following that tutorial as well.

**Comment by gino8080** [comment]
same here :(

**Comment by suresh-jbt** [comment]
@gino8080 @KALULOLO @ChristianKniep @MaciekStrzelbicki 
In the Ollama node configuration, use `http://host.docker.internal:11434` instead of `http://localhost:11434`.

Since Ollama is installed on the host machine and not within Docker, Docker containers cannot connect to the host’s services via `localhost`. By using `host.docker.internal`, you enable Docker to communicate with services on the host.
