### ISSUE TITLE
[BUG] Status: 500 Error: documentStoreServices.insertIntoVectorStore - SQLITE_READONLY: attempt to write a readonly database

### ISSUE THREAD

**Issue by SCHAT-spec** [FlowiseAI/Flowise#3351]
![2024-10-14 14 37 32](https://github.com/user-attachments/assets/f9416c3d-bffa-4d80-8b85-bf4b57b33b97)
![2024-10-14 14 37 44](https://github.com/user-attachments/assets/f2dc3b94-2e30-4d35-becf-939f6d880b61)
When I select ![2024-10-14 14 41 13](https://github.com/user-attachments/assets/402a682b-d476-4508-8199-992d48502686) I get this STatus Status: 500
Error: documentStoreServices.insertIntoVectorStore - SQLITE_READONLY: attempt to write a readonly database

**Setup**

-   `npx flowise start`
-   Flowise Version 2.1.2
-   Windows
-   chrome

Also Unable to 'Add New Document Store'

**Comment by AndersonNascimentoDosSantos** [comment]
The error you're encountering may be related to the location where the SQLite database file is being saved. I experienced a similar issue in a localhost environment due to the following environment configuration:

```env
DATABASE_PATH=/root/.flowise
APIKEY_PATH=/root/.flowise
SECRETKEY_PATH=/root/.flowise
LOG_PATH=/root/.flowise/logs
BLOB_STORAGE_PATH=/root/.flowise/storage
```

To resolve this issue, I recommend modifying the paths to a location where your application has the necessary read and write permissions. After adjusting the paths accordingly, the problem should be resolved.

Additionally, ensure that:
1. The specified directories exist and have the correct permissions.
2. Your application has sufficient privileges to access and modify these locations.
3. There are no conflicts with other processes or applications using the same paths.

If you continue to experience issues after making these changes, please provide more details about your specific environment and the exact error message you're receiving.

**Comment by HenryHengZJ** [comment]
thanks @AndersonNascimentoDosSantos ! Yes, you need to have read write permission to the database.
