### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by DewangS** [FlowiseAI/Flowise#3365]
I am running Flowise under Docker container on my Mac and noticed that there are many places in the user interface where there is no Save and Cancel buttons. i.e. once you make changes and click outside that popup window, your changes are saved by default. There is no way to discard your changes, if you change your mind. For example when you click the 'Additional Parameters' or 'Format Prompt Values' option on agents. The 'system Prompt' option does have 'Save' and 'Cancel' buttons. We would like consistent interface like this with 'Save' and 'Cancel' options on all input boxes.

**Comment by unfixa1** [comment]
That's a good suggestion. Thanks for your advice.
If you have used Docker, have you used [Servbay](servbay.com)? Maybe it's more suitable for you.

**Comment by HenryHengZJ** [comment]
We make this by default because having Save and Cancel on all input boxes can be alot and daunting for every changes you are making. It kinda depends on user preference. We think the work of having confirming every changes is not necessarily a better UX than automatically saving all the changes. Having said that, we might revisit in future to see if there is a better way to improve

**Comment by DewangS** [comment]
Thanks @HenryHengZJ though saving by default is kind of risky as you can save unwanted things as user changes their mind unless the UI provide a way to rollback to previous settings. Considering some of the dialog boxes are heavy with content and user needs to scroll a fair bit, may be a better option is to provide a popup confirmation dialog when user clicks outside the settings windows.
