### ISSUE TITLE
[BUG] RAG limitatoin to 99 entries?

### ISSUE THREAD

**Issue by j2l** [FlowiseAI/Flowise#3696]
**Describe the bug**
A CSV RAG for 366 days results in 99 records:
![Screenshot from 2024-12-12 21-31-03](https://github.com/user-attachments/assets/27ddf77a-e691-43f6-9f85-aa96d5f6a279)
Chat:
![Screenshot from 2024-12-12 21-32-36](https://github.com/user-attachments/assets/3c23d7ef-aae8-49a0-a344-45411675f5a1)
![Screenshot from 2024-12-12 21-34-13](https://github.com/user-attachments/assets/04fa48a4-798c-4a5d-a195-61fed851215a)

**To Reproduce**
Here are the files:
[tuto RAG Chatflow.json](https://github.com/user-attachments/files/18117237/tuto.RAG.Chatflow.json)
![image](https://github.com/user-attachments/assets/e7020903-63a4-4eb9-b6ee-3b7fc215c011)
[Daily_Light.csv.zip](https://github.com/user-attachments/files/18117234/Daily_Light.csv.zip)

**Expected behavior**
366 records to search in :smile: 

**Setup**
-   Installation docker
-   Flowise Version 2.2.1
-   OS: Ubuntu 22.04
-   Browser Chromium

**Comment by HenryHengZJ** [comment]
Normally its not recommended to use RAG for csv or tables related data. Because RAG is only suitable for kNN similarity search, meaning it will only fetch the k most relevant results to your query. However when it comes to table data, you do not want that, you want to search through whole table, and answer user query. For that, you can use CSV Agent, or even enable File Upload and directly upload from the chat interface.

**Comment by j2l** [comment]
Thank you very much @HenryHengZJ . Now I understand better.
In Flowise, is there a way to combine RAG result and map it back to their original CSV rows for the final response?
