### ISSUE TITLE
⚒️[FEATURE] Upstash Redis Memory

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/Flowise#372]
## Describe the feature you'd like
Upstash Redis Memory
Docs: https://js.langchain.com/docs/modules/memory/examples/upstash_redis

## ✅Tasks
- [ ] Add Upstash Redis Memory node

## 🎯Acceptance Criteria
- [ ] Upstash Redis Memory node should be able to remember conversations

## 👨‍💻How to contribute
Follow this [guide](https://github.com/FlowiseAI/Flowise/blob/main/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 👨‍💻Reference code
- [Zep Memory](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/memory/ZepMemory/ZepMemory.ts)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/jbaHfsRVBW)👾

**Comment by govind-kumarr** [comment]
@HenryHengZJ  I want to work on this. Can you assign this to me?

**Comment by ayushjain6013** [comment]
@HenryHengZJ Can you please review this PR https://github.com/FlowiseAI/Flowise/pull/1002.
I have tried adding support for upstash redis. Could see it coming in the workflow running locally but could not actually test it as i am unable to create a sample workflow because i do not have the paid subscription of GPT or any other language models. Can you help me test it?
