### ISSUE TITLE
[Question] Conversational vs Retrieval Conversational  Agents

### ISSUE THREAD

**Issue by mahmoudsorf** [FlowiseAI/Flowise#737]
I have done a lot of testing using these two agents. Conversational Agent was much better in respecting the prompts and gave less hallucinations. overall, the response quality was very good. The only issue with Conversational Agent is that it is does not support streaming and from a user experience perspective a delay in response is observed.

Switching to Retrieval Conversational Agent, response is much better, and streaming is supported BUT the agent is not respecting the full system prompt as Conversational Agent do specially when the conversation goes on with more back and forth calls (First questions the agent respects the system prompt but after like 5 or 6 question and answers if will start loosing it).

Any advice here, Also is thier a way to auto clear the context while a conversation is running when the agent feels that the response quality is getting lower.

**Comment by mahmoudsorf** [comment]
Please note all testing was done using GPT 3.5-turbo Model

**Comment by HenryHengZJ** [comment]
You can try OpenAI Function Agent and see.

Reason that Retrieval Conversational Agent might not respect the full prompt after more conversations is because this agent is using intermediate steps (reasoning, thoughts) to build the response, so the more context, the weaker it will stick to the original prompt

**Comment by zeitderforschung** [comment]
I guess for remembering intermediate steps as promoted in langchains blog post the Conversational Retrieval Agent requires the OpenAIAgentTokenBufferMemory, which is available in the Conversational Retrieval Agent Toolkit (another langchain abstraction).

It seems there are currently two ways to instantiate the CRA:
* [createConversationalRetrievalAgent](https://github.com/hwchase17/langchainjs/blob/357d6fccfc78f1332b54d2302d92e12f0861c12c/langchain/src/agents/toolkits/conversational_retrieval/openai_functions.ts#L15) with the advanced memory builtin
* [initializeAgentExecutorWithOptions](https://github.com/hwchase17/langchainjs/blob/357d6fccfc78f1332b54d2302d92e12f0861c12c/langchain/src/agents/initialize.ts#L108) with a configurable memory or simple buffer memory

I have added a [ConversationalRetrievalAgentToolkit](https://github.com/FlowiseAI/Flowise/commit/1689f05289d6dad9dcf4d8b9941bec2f15a3c45b) to our flowise fork. It works just fine. By the way, the original ConversationalRetrievalAgent in flowise sets the default system prompt to "You are a helpful AI assistant.", which is different to the langchain default of "Do your best to answer the questions. Feel free to use any tools available to look up relevant information, only if necessary.".

**Comment by mahmoudsorf** [comment]
@zeitderforschung, Thanks. hope it will get committed to the main branch as well.

**Comment by HenryHengZJ** [comment]
> @HenryHengZJ I guess for remembering intermediate steps as promoted in langchains blog post the Conversational Retrieval Agent requires the OpenAIAgentTokenBufferMemory, which is available in the Conversational Retrieval Agent Toolkit (another langchain abstraction).
> 
> It seems there are currently two ways to instantiate the CRA:
> 
> * [createConversationalRetrievalAgent](https://github.com/hwchase17/langchainjs/blob/357d6fccfc78f1332b54d2302d92e12f0861c12c/langchain/src/agents/toolkits/conversational_retrieval/openai_functions.ts#L15) with the advanced memory builtin
> * [initializeAgentExecutorWithOptions](https://github.com/hwchase17/langchainjs/blob/357d6fccfc78f1332b54d2302d92e12f0861c12c/langchain/src/agents/initialize.ts#L108) with a configurable memory or simple buffer memory
> 
> I have added a [ConversationalRetrievalAgentToolkit](https://github.com/FlowiseAI/Flowise/commit/524cee0c4dcb2dff5412a9b63f2aa6096fcd4e3a) to our flowise fork. It works just fine. By the way, the original ConversationalRetrievalAgent in flowise sets the default system prompt to "You are a helpful AI assistant.", which is different to the langchain default of "Do your best to answer the questions. Feel free to use any tools available to look up relevant information, only if necessary.".
> 
> Additionally we added source urls to the output of the RetrievalTool and told the agent to output the answer together with links to the sources when available. This was an huge improvement.

thank you so much for the improvement!! will take a look and definitely put it to Flowise!

**Comment by HenryHengZJ** [comment]
@zeitderforschung when you have the retrievertool to return answer all together with metadata source and title, how does that improve the agent response? as in like what difference have you noticed, with and without sources?

**Comment by zeitderforschung** [comment]
@HenryHengZJ Thanks for asking. Maybe I should talk about our use case first.

We have a large JSON lines file with a MediaWiki Export that includes the content, source url and title of the hundreds of wiki pages. This JSON Lines file is imported into a vector store. For this we have created a modified version of the JSON Lines Reader that also stores the source url and the page title for every json lines item (our documents) in the vector store.

What we want is a chatbot with the Conversational Retrieval Agent that we can ask about the wiki content and that not only shows us the answer from the wiki pages, but also includes nicely formatted markdown links in the answer, so that the user can jump to the source of the answer. For this we have created a version of the retriever tool that puts the source link in front of each text snippet. finally we had to change the system prompt of the agent to output the source links when available. The prompt looks like that: "Do your best to answer the questions. Feel free to use any tools available to look up relevant information, only if necessary. Always list markdown links contained in the corresponding answer of the tool."

So the improvement for us is, that there is an answer that contains cited sources with clickable markdown links. I think thats a common use case. As an alternative you can use a Conversational Retrieval Chain with source chips, but thats not as powerful as the agent version with embedded links and a more natural kind of conversation.

**Comment by HenryHengZJ** [comment]
@zeitderforschung thanks for the details explanation!
