### ISSUE TITLE
[BUG] conversationalRetrievalQAChain_0

### ISSUE THREAD

**Issue by AndyMik90** [FlowiseAI/Flowise#822]
conversationalRetrievalQAChain_0 in flowise does not use memory for a chat when hooked to a vector database.

Tested with two different memories

**Comment by HenryHengZJ** [comment]
Conversational Retrieval QA Chain has 2 passes:
1.) first pass it uses memory to rephrase the question
2.) 2nd pass it uses context to answer the rephrased question

You can also try out this template:
<img width="246" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/fc465056-cf34-489f-8a8b-f754fd6de6b8">

**Comment by AndyMik90** [comment]
So it's not supposed to work like a normal chat where it remembers its chat conversation? 
![conversationchain](https://github.com/FlowiseAI/Flowise/assets/119136210/5d792eb4-69e9-4542-83ec-91d2a0069529)
![Normal_Chain](https://github.com/FlowiseAI/Flowise/assets/119136210/ea7488bd-5de6-4fc3-8de9-a0d88028ac16)

The problem with the conversational agent is that it needs to support source documentation and Chain Option.

**Comment by HenryHengZJ** [comment]
Try Conversational Retrieval Agent:
<img width="1273" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/d1f05b16-f4e4-4a5d-abb0-1f107138d485">

**Comment by AndyMik90** [comment]
> Try Conversational Retrieval Agent: <img alt="image" width="1273" src="https://user-images.githubusercontent.com/26460777/262918140-d1f05b16-f4e4-4a5d-abb0-1f107138d485.png">

Yes that works, but Conversational Retrieval Agent  don't support source documentation and Chain Option.

**Comment by ustenkoo** [comment]
Hello colleagues, could you update will you plan to fix the current issue? 
Because we also have the same problem. 
If we use the chatbot without the Retriever tool, it has good answers from the document, but it doesn't remember what we asked him before. 
If we add the Retriever tool, it doesn't have good answers but remembers what he asked him before. Example: https://capture.dropbox.com/a8XlbmOO1xbi8aE3

We need both good answers according to the provided document and chat memory.

**Comment by HenryHengZJ** [comment]
We've revamped the Conversational QA Chain to be able to have human-like conversation and also retrieving from vector database. Retreiver Tool also now return source documents if used together with Agent
