### ISSUE TITLE
[BUG]  upsert multiple documents qdrant

### ISSUE THREAD

**Issue by jsu-github** [FlowiseAI/Flowise#834]
upsert multiple documents qdrant does not work. It returns: Error: Bad Request

I have tested both .txt and .docx files as input, both failed.

What is working fine:
- single document upsert

Upserting multiple documents in Pinecone works fine.

**Comment by Anush008** [comment]
Hey. I'm working on this issue.  Will circle back to you if I can come-up with a fix.

**Comment by jsu-github** [comment]
Sounds great!

John

**Comment by Anush008** [comment]
@jsu-github, I looked at the implementation and upserting multiple .txt and .pdf files works as expected.
Can you provide the error logs to see if we can get something.

> With PDF files
<img width="1160" alt="Screenshot 2023-09-10 at 1 36 35 PM" src="https://github.com/FlowiseAI/Flowise/assets/46051506/a700cd63-5d1e-4ba3-afec-119353bfd8c1">


> With text files
<img width="1160" alt="Screenshot 2023-09-10 at 1 40 01 PM" src="https://github.com/FlowiseAI/Flowise/assets/46051506/1534af77-1ee7-4565-98b2-6552ecbcbe30">

**Comment by ENGSamShamsan** [comment]
is this how we do multiple txt? i only see the option to upload one document???

**Comment by Anush008** [comment]
> is this how we do multiple txt? i only see the option to upload one document???

You can select multiple files from the file explorer.

**Comment by ENGSamShamsan** [comment]
that does not work for me 
<img width="2535" alt="Screen Shot 2023-09-26 at 10 24 09 PM" src="https://github.com/FlowiseAI/Fl
<img width="2233" alt="Screen Shot 2023-09-26 at 10 24 29 PM" src="https://github.com/FlowiseAI/Flowise/assets/41812691/c3d708a9-4766-4130-976f-f09da488da10">
owise/assets/41812691/d6ee5deb-bfb9-4c5e-9344-53217344c00d">

**Comment by ENGSamShamsan** [comment]
I am getting this error
<img width="2535" alt="Screen Shot 2023-09-26 at 10 24 09 PM" src="https://github.com/FlowiseAI/Flowise/assets/41812691/d14718c4-8a94-4c50-b2f0-37300ea535c9">

**Comment by Anush008** [comment]
I tried the same flow as yours. The upserting and retrieval worked fine for me. Can you confirm the collection is being created with your data from the Qdrant dashboard?

**Comment by ottkehe** [comment]
@Anush008 I don't know if this is related or if you can help me.

I notice that when I upload a document to QDrant using Flowise, it creates in qdrant a "content" field and when we use the [langchain code](https://python.langchain.com/docs/integrations/vectorstores/qdrant) it creates the field "page_content".

Because of that, I have an incompatibility when I try to chat with collections that I create using `qdrant-client`.

Any thoughts on that?
![Screen Shot 2023-10-27 at 21 05 16](https://github.com/FlowiseAI/Flowise/assets/106985483/aa87fb5c-8cb6-4eaf-be15-fd1ebf298099)

**Comment by DevOtts** [comment]
@Anush008 I don't know if this is related or if you can help me.

I notice that when I upload a document to QDrant using Flowise, it creates in qdrant a "content" field and when we use the [langchain code](https://python.langchain.com/docs/integrations/vectorstores/qdrant) it creates the field "page_content".

Because of that, I have an incompatibility when I try to chat with collections that I create using `qdrant-client`.

Any thoughts on that?
![Screen Shot 2023-10-27 at 21 05 16](https://github.com/FlowiseAI/Flowise/assets/106985483/aa87fb5c-8cb6-4eaf-be15-fd1ebf298099)
