### ISSUE TITLE
[BUG] Troubles with DynamoDB integration

### ISSUE THREAD

**Issue by LucasKnudsen** [FlowiseAI/Flowise#871]
**Describe the bug**
I'm attempting to setup memory with the DynamoDB Chat Memory integration. 
However, it does not seem to create any entries in the database. I have attached a couple screenshots to help visualise the issue. 
As shown, there is indeed Scan and DeleteItem (odd?) activity, which means that the connection is live. 

What am I doing wrong here?
Related to #370 and #454 
@govind-kumarr 

**Expected behavior**
I expect some sort of Chatlog record to be stored in the appointed Table.

**Screenshots**
<img width="710" alt="Screenshot 2023-09-03 at 19 24 59" src="https://github.com/FlowiseAI/Flowise/assets/75306727/28f34a37-ea2e-4422-9a40-1b3112a1a218">
<img width="387" alt="Screenshot 2023-09-03 at 19 37 21" src="https://github.com/FlowiseAI/Flowise/assets/75306727/df9f8492-ffa6-4c27-b6cb-32860b4b3130">

<img width="397" alt="Screenshot 2023-09-03 at 19 18 35" src="https://github.com/FlowiseAI/Flowise/assets/75306727/ec7aa68c-92e6-4306-9bd9-c783a56e6689">
<img width="449" alt="Screenshot 2023-09-03 at 19 18 54" src="https://github.com/FlowiseAI/Flowise/assets/75306727/5a756b8c-11c6-47f2-abdd-21c6137d4f24">
<img width="772" alt="Screenshot 2023-09-03 at 19 23 22" src="https://github.com/FlowiseAI/Flowise/assets/75306727/3267e785-9818-4dda-9abb-a1e348722e00">

**Comment by lucas-bsq** [comment]
Experienced the same thing. The conversation is stored to the local SQLite but not in DynamoDB.

**Comment by meehow-m** [comment]
the issue is related to:

https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.ts

line 182:

<img width="1038" alt="CleanShot 2023-09-20 at 20 45 57@2x" src="https://github.com/FlowiseAI/Flowise/assets/97568112/e0ca56f1-e1e2-4e74-879c-a63daf669ad5">


`mapChatHistory` returns `ChatMessageHistory` interface but `BufferMemoryExtended` is expected. which means connection is dropped and DynamoDB does not save anything. I'm building knowledge around `langchain-js` so need some time to fix it but at least root cause was identify.

```
BufferMemoryExtended {
  chatHistory: DynamoDBChatMessageHistory {
    lc_serializable: false,
    lc_kwargs: {},
    lc_namespace: [ 'langchain', 'stores', 'message', 'dynamodb' ],
    tableName: 'flowise',
    sessionId: '123',
    client: DynamoDBClient { middlewareStack: [Object], config: [Object] },
    partitionKey: 'id',
    sortKey: undefined,
    messageAttributeName: 'messages',
    dynamoKey: { id: [Object] }
  },
  returnMessages: true,
  inputKey: 'question',
  outputKey: 'text',
  humanPrefix: 'Human',
  aiPrefix: 'AI',
  memoryKey: 'chat_history',
  isSessionIdUsingChatMessageId: true,
  sessionId: '123'
}
```

result: 
<img width="1380" alt="CleanShot 2023-09-20 at 20 53 04@2x" src="https://github.com/FlowiseAI/Flowise/assets/97568112/7231e6d9-eca6-41ac-b968-363ec7f04020">

**Comment by HenryHengZJ** [comment]
this PR should fix that - https://github.com/FlowiseAI/Flowise/pull/1025
try to update to latest v1.3.8, feel free to re-open if issue persist
